name: spades_customer_service
description: ♠♠ SPADES Boardgame Coffee © ♠♠

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.15.0
  cloud_firestore: ^4.9.5
  firebase_auth: ^4.14.0
  provider: ^6.1.1
  intl: ^0.19.0
  image_picker: ^1.0.4
  firebase_storage: ^11.2.0
  cached_network_image: ^3.3.0
  chewie: ^1.5.2
  video_player: ^2.8.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true